language: node_js
node_js:
  - "6"

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

dist: trusty

before_script:

  - npm i -g @magnolia/cli
  - mgnl -h

  - cd .. && mkdir -p magnolia && cd magnolia && mgnl jumpstart && cd ..

  - cd mgnl-custom && npm run build && cd ..

  - cp -R mgnl-custom magnolia/light-modules/
  - cp magnolia/light-modules/mgnl-custom/dev/test/fixtures/website.ci-testpage.xml magnolia/apache-tomcat/webapps/magnoliaAuthor/WEB-INF/bootstrap/common
  - ls magnolia/apache-tomcat/webapps/magnoliaAuthor/WEB-INF/bootstrap/common

  - cat magnolia/apache-tomcat/webapps/magnoliaAuthor/WEB-INF/config/default/magnolia.properties | grep magnolia.resources.dir
  - mkdir -p magnolia/apache-tomcat/logs/
  - touch magnolia/apache-tomcat/logs/catalina.out
  - pwd && ls
  - cd magnolia
  - mgnl start &
  - until fgrep -q "Server startup" apache-tomcat/logs/catalina.out; do sleep 1; done

  - cd ..
  - cd mgnl-custom
  - curl http://localhost:8080/magnoliaPublic/ci-testpage.html
  - curl http://localhost:8080/magnoliaPublic/ci-testpage.html | grep "furbie"
