language: node_js
node_js:
  - "6"

sudo: required

before_script:
  - cd .. && git clone -b proto https://github.com/robertkowalski/magnolia-cli
  - cd magnolia-cli && npm i -g .
  - mgnl -h
  - cd .. && mkdir -p magnolia && cd magnolia && mgnl jumpstart
  - cd ..
  - ls
  - cp -R mgnl-custom magnolia/light-modules/
