language: node_js
node_js:
  - "6"

env:
  - MAGNOLIA_CE_VERSION=5.5.1

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default

dist: trusty

before_script:

  - cd .. && git clone -b proto https://github.com/robertkowalski/magnolia-cli && cd magnolia-cli && npm i -g . && cd ..
  - mgnl -h
  # - mkdir -p magnolia && cd magnolia && mgnl jumpstart && cd ..
  - curl -fSL https://nexus.magnolia-cms.com/content/repositories/magnolia.public.releases/info/magnolia/bundle/magnolia-community-demo-bundle/$MAGNOLIA_CE_VERSION/magnolia-community-demo-bundle-$MAGNOLIA_CE_VERSION-tomcat-bundle.tar.gz -o magnolia.tar.gz
  - mkdir magnolia && tar -xzf magnolia.tar.gz -C magnolia --strip-components=1
  - TOMCAT_FOLDER=$(ls magnolia | grep apache)

  - ls

  - cd mgnl-custom && npm run build && cd ..

  - mkdir -p magnolia/light-modules/mgnl-custom
  - cp -R mgnl-custom magnolia/light-modules/mgnl-custom
  - ls magnolia/light-modules/
  - ls magnolia/light-modules/mgnl-custom
  - ls magnolia/light-modules/mgnl-custom/dev
  - ls magnolia/light-modules/mgnl-custom/dev/test
  - ls magnolia/light-modules/mgnl-custom/dev/test/fixtures

  - cp magnolia/light-modules/mgnl-custom/dev/test/fixtures/website.ci-testpage.xml magnolia/$TOMCAT_FOLDER/webapps/magnoliaAuthor/WEB-INF/bootstrap/common

  - mkdir -p magnolia/$TOMCAT_FOLDER/logs/
  - touch magnolia/$TOMCAT_FOLDER/logs/catalina.out
  - pwd && ls
  - cd magnolia
  - mgnl start &
  - cd ..

  - until fgrep -q "Server startup" magnolia/$TOMCAT_FOLDER/logs/catalina.out; do sleep 1; done

  - cd ..
  - cd mgnl-custom
