language: node_js
node_js:
  - "6"

sudo: required

before_script:
  - cd .. && git clone -b proto https://github.com/robertkowalski/magnolia-cli
  - cd magnolia-cli && npm i -g .
  - mgnl -h
  - cd .. && mkdir -p magnolia && cd magnolia && mgnl jumpstart
  - cd ..
  - ls
  - cp -R mgnl-custom magnolia/light-modules/
  - cp magnolia/light-modules/mgnl-custom/dev/test/fixtures/website.ci-testpage.xml magnolia/apache-tomcat/webapps/magnoliaAuthor/WEB-INF/bootstrap/common
  - ls magnolia/apache-tomcat/webapps/magnoliaAuthor/WEB-INF/bootstrap/common
  - mkdir -p magnolia/apache-tomcat/logs/
  - touch magnolia/apache-tomcat/logs/catalina.out
  - pwd && ls
  - cd magnolia
  - mgnl start &
  - until fgrep -q "Server startup" apache-tomcat/logs/catalina.out; do sleep 1; done
  - echo "server started"

  - cd mgnl-custom

script:
  - curl -u superuser:superuser http://localhost:8080/magnoliaPublic/.rest/nodes/v1/website/ci-testpage

  - curl -u superuser:superuser http://localhost:8080/magnoliaPublic/.rest/nodes/v1/website/ci-testpage | grep "furbie"
